SELECT 
	ID, replace(replace(replace(replace(replace(replace(replace(replace(CAST(RECLAMACAO AS CHAR CHARACTER SET utf8),':',' '), '\n',' '),'|',' '),'\r',' '),';',' '),',', ''),'/',' '),'\\',' ') AS RECLAMACAO, 
     UF, CIDADE, SERVICO, MOTIVO, SUBMOTIVO, TIPO_ATENDIMENTO

 from ML_BASE_TREINO INTO OUTFILE '/tmp/dados_ml.csv' FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' LINES TERMINATED BY '\n';
 
 SELECT @@character_set_database;
 
ALTER DATABASE machinelearning CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE ML_BASE_TESTE CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;

select R.SERVICO,count(R.SERVICO) from ML_BASE_TESTE R GROUP BY R.SERVICO;

CREATE TABLE ML_BASE_TREINO AS SELECT * FROM ML_RECLAMACOES_CLARO WHERE SERVICO IN ('Celular Pós-Pago','Celular Pré-Pago','Móvel Pessoal') LIMIT 1;

INSERT INTO ML_BASE_TREINO SELECT * FROM ML_BASE_SEM_OUTLIEAR WHERE SERVICO = 'Celular Pós-Pago' limit 200000;
INSERT INTO ML_BASE_TREINO SELECT * FROM ML_BASE_SEM_OUTLIEAR WHERE SERVICO = 'Celular Pré-Pago' limit 100000;
INSERT INTO ML_BASE_TREINO SELECT * FROM ML_BASE_SEM_OUTLIEAR WHERE SERVICO = 'Móvel Pessoal' limit 100000;


INSERT INTO ML_BASE_TESTE SELECT * FROM ML_BASE_SEM_OUTLIEAR t1 WHERE t1.ID NOT IN (SELECT t2.ID FROM ML_BASE_TREINO t2);

DELETE FROM ML_BASE_TESTE;
SELECT COUNT(*) FROM ML_BASE_TESTE;

SELECT * FROM ML_BASE_TESTE WHERE RECLAMACAO IS NOT NULL or RECLAMACAO != '' LIMIT 1;

